spring:
 datasource:
   url: jdbc:mariadb://mysql-marien.alwaysdata.net/marien_db
   password:  ElisaMathis@2023
   username:  marien_taps
   driver-class-name: org.mariadb.jdbc.Driver
 jpa:
   hibernate:
     ddl-auto: update  
   show-sql: true
   
